### ISSUE TITLE
Documentation: Ports exposed twice

### ISSUE THREAD

**Issue by tmberthold** [catenax-ng/product-edc#103]
If I see it correctly there is an overlap in the docker run commands of the ports to expose in the documentation of the following combination (didnt look up the others). This is no major problem if you know this and can fix it on the fly, otherwise the latter of the two planes cannot be started, whichever you start second, as ports to be exposed are already in use.

```
docker run \
    -p 8080:8080 -p 8181:8181 -p 8182:8182 -p 8282:8282 -p 9090:9090 -p 9999:9999 \
```
https://github.com/catenax-ng/product-edc/tree/develop/edc-controlplane/edc-controlplane-memory

```
docker run \
  -p 8080:8080 -p 8185:8185 -p 9999:9999 -p 9090:9090 \
```
https://github.com/catenax-ng/product-edc/tree/develop/edc-dataplane

**Comment by florianrusch-zf** [comment]
In my point of view this is not a bug. You toke two different commands from two different files 😉 
If we would arrange this two commands on our side, we should also support starting multiple instances of one of them (e.g. two dataplane instances). This makes things more complex and so on. Therefor we decided within the team, to leaf this as it is.
