### ISSUE TITLE
Publish packages from main / on merge main to github packages

### ISSUE THREAD

**Issue by domreuter** [catenax-ng/product-edc#66]
_If you are missing a feature or have an idea how to improve this project that should first be 
discussed, please feel free to open up a [discussion](https://github.com/catenax-ng/catena-x-edc/discussions/categories/ideas)._

**Is your feature request related to a problem? Please describe.**
"product"-edc should be used within the catenaX@home, therefore it would be nice to reference to prebuild packages within gradle

**Describe the solution you'd like**
base this project on published packages on maven central as it is discussed in the [oss repo here](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/404)

**Describe alternatives you've considered**
- publish packages to the catenax-ng github packages
- publish packages on every merge /commit on main

**Comment by florianrusch-zf** [comment]
We will not publish packages that are not source of this repository. This should be done by the oos repo.
Of course we will somewhen publish our own extensions into github packages.

For reference take a look at #90
