### ISSUE TITLE
Control Plane Documentation: Describe DAPS Conversion for KeyVault Import

### ISSUE THREAD

**Issue by DominikPinsel** [catenax-ng/product-edc#87]
The Catena-X DAPS team is handing out keys and certificates in a format, that cannot be processed by the EDC connector. Therefore, it is necessary to do a conversion before uploading them to the Key Vault.

The necessary documentation should be added to  [/edc-controlplane/README.md](https://github.com/catenax-ng/product-edc/tree/develop/edc-controlplane).

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

**Comment by florianrusch-zf** [comment]
Not necessary anymore, because the EDC supports the provided file formats.
